name: Build and deploy a container image to Azure Web Apps

on:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: mass-bot
  CONTAINER_REGISTRY: ${{ secrets.REGISTRY_URL }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main

    - name: Authenticate using a Service Principal
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }}
      
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Docker Build & Push to ACR
      run: |
          docker build . -t ${{ env.CONTAINER_REGISTRY }}/mass-bot/mass-bot:${{ github.sha }}
          docker push ${{ env.CONTAINER_REGISTRY }}/mass-bot/mass-bot:${{ github.sha }}

    - name: Update image tag on the Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        images: ${{ env.CONTAINER_REGISTRY }}/mass-bot/mass-bot:${{ github.sha }}
        startup-command: 'python bot/__init__.py'