name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: froduxcontainerregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: |
          docker build . -t froduxcontainerregistry.azurecr.io/mass-bot/mass-bot:${{ github.sha }} -t ${{ secrets.DOCKER_USERNAME }}/mass-bot:${{ github.sha }}
          docker push froduxcontainerregistry.azurecr.io/mass-bot/mass-bot:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/mass-bot:${{ github.sha }}